[template]
ignore = ["readme.md"]

[hooks]
init = ["init-script.rhai"]

[conditional.'skip_config == true']
ignore = [
    "rust-toolchain.toml",
    ".cargo",
    ".cargo/config.toml",
    "kde_rule.kwinrule",
]
